directories:
  output: release
  buildResources: electron/build
appId: com.poetry.zhixue
productName: 智韵灵犀
copyright: Copyright © 2024
files:
  - filter:
      - electron/main.js
      - backend/**/*
      - '!backend/node_modules/.cache/**/*'
      - '!backend/src/**/*'
      - poetry/**/*
      - nodejs/**/*
      - package.json
extraResources:
  - from: nodejs
    to: nodejs
  - from: poetry
    to: poetry
asar: false
win:
  target:
    - target: dir
      arch:
        - x64
    - target: portable
      arch:
        - x64
  icon: backend/public/run.jpg
  artifactName: ${productName}-${version}-${arch}-portable.exe
portable:
  artifactName: ${productName}-${version}-portable.exe
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  installerIcon: backend/public/run.jpg
  uninstallerIcon: backend/public/run.jpg
  installerHeaderIcon: backend/public/run.jpg
  createDesktopShortcut: true
  createStartMenuShortcut: true
  shortcutName: 智韵灵犀
electronVersion: 28.0.0
